In [1]:
%load_ext autoreload
%autoreload 2

In [7]:
from lab2.utils import get_random_number_generator
import numpy as np

from lab2.box_window import BoxWindow
from lab2.ball_window import BallWindow
from lab2.box_window import UnitBoxWindow

In [3]:
ball = BallWindow([3, 2, 4], 2)

In [4]:
ball.volume(), ball.area()

('The volume is 33.51', 'The area is 50.27')

In [57]:
ball.__str__()

'A ball with center= [1 2] and radius= 1'

In [84]:
ball.__contains__([0, 6])

True

In [80]:
a = np.array([1, 2])
b = np.array([3, 1])
a - b

array([-2,  1])

In [53]:
type(ball.radius)

int

In [3]:
type(2.0)


float

In [15]:
box = UnitBoxWindow([1, 20],2, [[1, 2], [1,2]])

TypeError: __init__() takes 3 positional arguments but 4 were given

In [59]:
box.__str__()

'BoxWindow: [0, 20] x [-10, -6] x [-5, 5]'

In [43]:
box.length()

[20, 4, 10]

In [42]:
box.center()


array([10., -8.,  0.])

In [10]:
box.__contains__([1,2])

True

In [22]:
box.center()

array([0., 0., 0.])

In [20]:
box.volume()

2

In [23]:
type(0.)

float