# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Capucine GARCON]([link](https://github.com/CapucineGARCON))
- [Student 2]([link](https://github.com/username2))

In [5]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

In [6]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [89]:
A1 = np.ones((1, 100))
A2 = np.array([1 for i in range (100)])

A1, A2


(array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

Create a vector with values ranging from 10 to 49

In [73]:
B = np.arange(10, 50)
B

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [76]:
C = np.arange(0, 0.9, 0.2)
C

array([0. , 0.2, 0.4, 0.6, 0.8])

Convert a float array into an integer array in place

In [91]:
# Convertion of a float array into an integer array
C1 = np.arange(0, 0.9, 0.2)
C2 = C1.astype(int)
C1, C2


(array([0. , 0.2, 0.4, 0.6, 0.8]), array([0, 0, 0, 0, 0]))

Given a boolean array

- return the indices that are True 
- negate the array inplace 

In [142]:
M = np.array([[True, True, False, True, False, False]])

# Two methods to return the indices that are True 
j = np.where(M == True)
i =np.flatnonzero(M == True)


# Negation of M: two methods 
N = ~M
N2 = np.invert(M)


Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [102]:
# Inner product
u = np.array([1, 2, 3])
v = np.array([2, 2, 1])

np.dot(u,v), u @ v




(9, 9)

In [101]:
# Outer product 
np.outer(u,v)

array([[2, 2, 1],
       [4, 4, 2],
       [6, 6, 3]])

In [103]:
# Outer sum matrix 

np.add.outer(u,v)

array([[3, 3, 2],
       [4, 4, 3],
       [5, 5, 4]])

Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [3]:
# Creation of M using a list of list 

M = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

M[1][1]

4

In [104]:
# Creation of M using numpy: 3 methods 
M = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

N = np.arange(0, 9)
N.shape = (3, 3)

O = np.matrix('[0, 1, 2; 3, 4, 5; 6, 7, 8]')
M[1][1]




4

In [21]:
# Swap first and second raw

M[0], M[1] = M[1], M[0]
M

array([[3, 4, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
# Extraction of the submatrix

M[1:3, 1:3], 

array([[4, 5],
       [7, 8]])

In [108]:
# Extraction of the diagonal

np.diag(M), M.diagonal(), [M[i][i] for i in range(len(M))]



(array([0, 4, 8]), array([0, 4, 8]), [0, 4, 8])

In [109]:
# Calculation of M^3

M_cube1 = np.dot(M,np.dot(M,M))
M_cube2= np.linalg.matrix_power(M, 3)
M_cube3 = M @ M @ M
M_cube1, M_cube2, M_cube3

(array([[ 180,  234,  288],
        [ 558,  720,  882],
        [ 936, 1206, 1476]]),
 array([[ 180,  234,  288],
        [ 558,  720,  882],
        [ 936, 1206, 1476]]),
 array([[ 180,  234,  288],
        [ 558,  720,  882],
        [ 936, 1206, 1476]]))

In [49]:
# Calculation of vTM
M = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
v = np.array([1, 2, 3])
np.dot(np.transpose(v), M)

array([24, 30, 36])

In [47]:
# Vectorisation of the matrix M
M = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

M_vect = tuple(np.ravel(M, order ='C'))
M_vect2 = tuple(np.ravel(M, order='F'))

M_vect, M_vect2





((0, 1, 2, 3, 4, 5, 6, 7, 8), (0, 3, 6, 1, 4, 7, 2, 5, 8))

In [34]:
v = np.array([1, 2, 3])
np.dot(v, M), np.dot(M,v)

(array([24, 30, 36]), array([ 8, 26, 44]))

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [57]:
# Check if the matrix is symmetric or not
def is_symmetric(M):
    return(np.all(M == np.transpose(M)))


is_symmetric(M = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])), is_symmetric(np.array([[1, 2, 3],[2, 0, 2], [3, 2, 1]]))
    

(False, True)

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

In [114]:
# Generation of 1000 samples

rng = get_random_number_generator(0)
first_way = rng.binomial(1, 0.4, 1000)


In [117]:
# Calculation of mean and variance

np.mean(first_way), np.var(first_way)

(0.419, 0.243439)

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column

In [129]:
# Computation of the Gaussian Matrix of size 50x100
G = rng.normal(size = (50, 100))

# Absolute value of the Gaussian Matrix
G_absolute = abs(G)

#Sum of each row 
G_sum_rows = G.sum(axis=1)

# Sum of each colomn
G_sum_colomn = G.sum(axis=0)

# Norm of each row
G_norm_row = np.linalg.norm(G, axis=1)

# Norm of each colomn
G_norm_colomn = np.linalg.norm(G, axis = 0)
